[build]
  publish = ".next"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--version"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  NODE_ENV = "production"
  NEXT_PUBLIC_CHANNEL_TALK_PLUGIN_KEY = "ac1cd793-222d-4538-ac20-8ae1e9d313d0"

[context.deploy-preview.environment]
  NODE_ENV = "production"
  NEXT_PUBLIC_CHANNEL_TALK_PLUGIN_KEY = "ac1cd793-222d-4538-ac20-8ae1e9d313d0"